services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
      - 5432:5432
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actix -d actix"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  todo-actix:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8080
      PG.USER: actix
      PG.PASSWORD: actix
      PG.HOST: postgres
      PG.PORT: 5432
      PG.DBNAME: actix
      PG.POOL.MAX_SIZE: 30
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Add this networks section at the bottom
networks:
  app-network:
    driver: bridge